name = "Split Extended"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "//github.com/dapode/hugo-splitex-theme/blob/master/LICENSE.md"
description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
homepage = "//github.com/dapode/hugo-splitex-theme"
tags = ["minimal", "responsive", "personal"]
features = []
min_version = "0.22"

[author]
  name = "Christian Mendoza / Felix Börner / dapode"

# If porting an existing theme
[original]
  name = "One Page Love"
  homepage = "//onepagelove.com/split"
  repo = ""
